language: node_js
node_js: 7
cache:
  directories:
  - node_modules
  - bower_components
  - "${NVM_PATH}_modules"
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
install:
- npm install

script: echo "Deploying!"
before_deploy: 
  - npm run build
  - if [ "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then make configure-prod ; fi
  - if [ "$TRAVIS_BRANCH" = "develop" -a "$TRAVIS_PULL_REQUEST" = "false" ]; then make configure-dev ; fi
deploy:
- provider: firebase
  skip_cleanup: true
  on:
    branch: master      # on which branch trigger build
    tags: true
  project: cs3-krakow-2018   # Firebase project name
  token:
    secure: "MzxgEy9kHKSzIrlEJ0MQ9o5eA1f9IhVx6KrODLAhi2qspmlfKUyiN6Zs1tkvlToqswoHLS6rF2txa+wHRwwXE3aLaszzySoTkki9knleA/Zv7qZ/mjpqCNPGFeOWN37SdCOlUWCL6d8cbIY3MoQ8GGOQa3WO4Dt7+XtgQiWDM0x5+SEjwAK1J08oZjwHZUYBALeUP+Vku89tE5Rl3H/Bv+vF8Ko/cla+QJKxm/2/2EhYF3CEAIkGc+pKtHZxk+SWjhF9H4GenfiBrsQzZTYEQOyElb69dOMa5vS129ZijMObU5XMARJOiZrDvKgiCgiGARAlPJWmRT9+7PddmNZRP+WpNxhBGHKYuNIKAnltnpVOZtgd8FJGTkdtTuysfaRUF/LvXG/hX22c8dWpwJ5NYniIeLZJ+fvtHRn6s9Kfy4DIKlpT6FMRLk/CopGD6s5JGWeBimr61HTsOtTHESsC0Qj339ddJMsTjeuD5Kt3oZgNAnXiDB5l2L6SyqzLvO9Gw4dKaYIepwAaXz8x8iIYjbtPTmVf764/UwYRCE6NwvigUMZuLloFZYuxcKf1a+wbG052N6dfdcboLc1b8EwLdJaFkk0nHcUc6JDjRkYsqLBkS5lOFdvG8uskjktqqlOWORXhVtmJEYsBcqt8WiI1pxnP32VG7jTNKtaWyZ5/wQo="
- provider: firebase
  skip_cleanup: true
  on:
    branch: develop      # on which branch trigger build
  project: cs3-krakow-2018-dev   # Firebase project name
  token:
    secure: "RX7fbzPLj5Dwik5kQQ9gSlt9HynuLEJeHKIPENQCzm0HiagSkzJvWMP7cPjocnXdohtwMlXjYFp+dm8dkA0EYJA+4vZztD00fZbPQp+W47uMpkmaloGkYQqJE7REr+eGv8SfvenGv5r1Lnf2fPjJbRHIwyV1p/I9wNGtRnucvKWM0Sfy7dshHzom41eh9dOiKOyGn8aGEZoGJBm0KyhSvHzrw9Nh0/EVNJF9bc6XTIFs/FZSPx7ua95AtazDASJQCBNFCT96Xy6USIHFDNmUCTZBiHdcH19b5lbn1KIqEXeJ5Ob4U/H43gV5XEVvRHjfbymJipEHf7oie6+Ae5s6AfaQ9yOcle2DMpsWZDrny0jHEXUkAemyO5xLvI70gxQ0VLSPylclag4R8C+fnFYFNSy/tzYLjyh/BGgd6A0zxz6uL1obMnz9kNJ1bmdcVEztWap6TPPsO3D7OXhsru3vP4F6odzxuarZfmSbeSWrSgLXIoT+W8dOcn4eS1//M4nrgCIEqDXm0WboDvMNNDgdbyJLfa6oEe6SBFSh50Bk7AUd7ADHBeYgVEF12mZjZ/JHyoxFCtYYv7P6t9GY1mh4u77Lv9HEvCB3FuxMOgiA2bDFbl7tvcM5DmtGiPBIEfRnxQ1o/sVFJ7sBMoab6lXvoIbUa6avlAiTLLXWnOHOeVA="